
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150
MAX_LENGTH_USERNAME = 150
VALID_USERNAME_REGEX = r'^[\w.@+-]+$'
MAX_LENGTH_TAG_NAME = 32
MAX_LENGTH_INGRIDIENT_NAME = 128
MAX_LENGTH_RECIPE_NAME = 256
