# Generated by Django 3.2.3 on 2024-12-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_id',
            field=models.CharField(blank=True, help_text='Короткое значение ссылки рецепта', max_length=8, unique=True),
        ),
    ]
